[[redirects]]
  from = "/api/*"
  to = "http://mokaform.site/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
 for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "http://mokaform.site"