[[redirects]]
  from = "https://feat-deploy--papaya-horse-fada9b.netlify.app/"
  to = "http://210.109.60.220:8080/:aplat"
  status = 200
  force = true

[[headers]]
 for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"