[[redirects]]
  from = "/api"
  to = "http://210.109.60.220:8080"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
 for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"