[[redirects]]
  from = "/api/*"
  to = "http://210.109.60.220:8080/api/:splat"
  status = 200
  force = true

[[headers]]
 for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"