[[redirects]]
  from = "/*"
  to = "http://ip-210-109-60-220.c.kr-central-1.kakaokic.com.:8080"
  status = 200

[[headers]]
 for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"