[[redirects]]
  from = "/api/*"
  to = "http://www.mokaform.site/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
 for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"