apiVersion: v1
kind: Service
metadata:
  name: frontend-service-argo
spec:
  selector:
    app: mokaform-argo
    tier: frontend
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31001
    targetPort: 80
